[package]
name = "nosapi_data"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
md5 = "0.7.0"
pelite = "0.10.0"
schemars = { version = "0.8.12", optional = true }
serde = { version = "1.0.185", features = ["derive"], optional = true }
thiserror = "1.0.47"

[dev-dependencies]
serde_json = "1.0.105"
anyhow = "1.0.75"

[features]
default = []
serde = ["dep:serde", "serde/derive"]
json_schema = ["dep:schemars"]

