import "~/styles/globals.css";
import { clsx } from "clsx";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx("font-sans", inter.variable)}>{children}</body>
    </html>
  );
}
