name: Continuous Deployment

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  pre-release:
    name: pre-release
    if: "${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'chore: release') }}"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: configure git
        run: |
          git config --global user.name GitHub Actions
          git config --global user.email github-actions@github.com
      - name: install nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ github.token }}
      - name: nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: create release pr
        run: nix develop -L --fallback --accept-flake-config --command knope pre-release --verbose
        continue-on-error: true
  release:
    name: release
    if: "${{ github.event_name == 'pull_request' && github.head_ref == 'chore/release' && github.event.pull_request.merged == true }}"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ github.token }}
      - name: nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: create release pr
        run: nix develop -L --fallback --accept-flake-config --command knope release --verbose
