name: CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: read

jobs:
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'zakuciael' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure binary cache
        uses: Mic92/niks3-action@v1
        with:
          server-url: https://cache.zakku.eu
      - name: Configure sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: Create release
        run: devenv shell release-plz release --git-token "${{ secrets.GITHUB_TOKEN }}" --forge github

  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'zakuciael' }}
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure binary cache
        uses: Mic92/niks3-action@v1
        with:
          server-url: https://cache.zakku.eu
      - name: Configure sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: Create Release PR
        run: devenv shell release-plz release-pr --git-token "${{ secrets.GITHUB_TOKEN }}" --forge github
