name: Continuous Deployment

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-release:
    name: pre-release
    if: "${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'chore: release') }}"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: configure git
        run: |
          git config --global user.name GitHub Actions
          git config --global user.email github-actions@github.com
      - name: install knope
        uses: knope-dev/action@v2.1.0
        with:
          version: "0.20.0"
      - name: create release pr
        run: knope pre-release --verbose
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  release:
    name: release
    if: "${{ github.event_name == 'pull_request' && github.head_ref == 'chore/release' && github.event.pull_request.merged == true }}"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          matcher: true
      - name: install knope
        uses: knope-dev/action@v2.1.0
        with:
          version: "0.20.0"
      - name: create release pr
        run: knope release --verbose
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
