name: Continuous Deployment
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    name: publish crates
    if: (github.head_ref == 'knope/release' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          matcher: true
      - name: run cargo publish
        run: cargo release publish --workspace --no-confirm --execute
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
