name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  flake:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ github.token }}
      - name: nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: check flake.lock
        uses: DeterminateSystems/flake-checker-action@v9
      - name: nix flake check
        run: nix flake check -L --option sandbox true
  format:
    name: treefmt
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ github.token }}
      - name: nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: treefmt
        uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: .#default
          exportEnv: false
          interpreter: bash
          extraNixOptions: --option sandbox true
          script: treefmt --ci
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          matcher: true
      - name: cargo clippy
        run: cargo clippy --workspace -- --deny warnings
  cargo-test:
    name: cargo nextest (${{ matrix.os }})
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          matcher: true
      - name: install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: cargo nextest
        run: cargo nextest run
  # TODO: Add builds for node bindings for all supported platforms
  # TODO: Add tests for node bindings for all supported platforms
