name: CI

on:
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint packages
        run: pnpm lint --filter="...[origin/${{ github.base_ref }}]" -- --format=compact
  format:
    runs-on: ubuntu-latest
    name: Prettier
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Validate code style
        run: pnpm format:check --filter="...[origin/${{ github.base_ref }}]"
  typescript:
    runs-on: ubuntu-latest
    name: TypeScript
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Register Problem Matcher
        run: echo "##[add-matcher].github/tsc.json"
      - name: Validate types
        run: pnpm typecheck --filter="...[origin/${{ github.base_ref }}]"
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test --filter="...[origin/${{ github.base_ref }}]"