name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  id-token: write

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # This runs: format checks (via treefmt), clippy (via git-hooks)
  build-shell-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure binary cache
        uses: Mic92/niks3-action@v1
        with:
          server-url: https://cache.zakku.eu
      - name: Configure sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: Build the devenv shell and lint codebase
        run: devenv test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure binary cache
        uses: Mic92/niks3-action@v1
        with:
          server-url: https://cache.zakku.eu
      - name: Configure sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: Build all crates
        run: devenv tasks run nosapi:build:release
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure binary cache
        uses: Mic92/niks3-action@v1
        with:
          server-url: https://cache.zakku.eu
      - name: Configure sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: Run unit tests
        run: devenv tasks run nosapi:test
