name: Validate PR

on:
  pull_request_target:
    branches: [ "*" ]

jobs:
  pr_title:
    runs-on: ubuntu-latest
    name: Validate PR title
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}