name: Release

on:
  push:
    branches: [ "main" ]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    if: ${{ github.repository_owner == 'zakuciael' }}
    runs-on: ubuntu-latest
    name: Changeset
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check for errors
        run: pnpm check --filter="./packages/*"
      - name: Build packages
        run: pnpm build --filter="./packages/*"
      - name: Create PR or publish to NPM
        uses: changesets/action@v1.4.1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: pnpm release
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}